AudiusProject/general-admission

nginx/nginx.template
Tested:
Updated staging https://general-admission.staging.audius.co/embed/api.js
=> Proxy pass api.js

src/servlets/protocolDashboard/index.ts
Moving this logic into the Protocol Dashboard CI flow.
=> Change peer to return content nodes

src/servlets/bedtime/index.ts, src/servlets/bedtime/types.ts
Send gateways back in embed resp.
Corresp. change in bedtime https://github.com/AudiusProject/bedtime/pull/23
=> Fix playback

.env.prod, .env.stage, nginx/nginx.template, src/index.ts, src/servlets/ipfs/index.ts
moves /protocolDashboard -> /ipfs to make it more generic for any static site
=> Support multiple IPFS sites

src/servlets/utils/constants.ts
Added the info and link to img for remixables to the exploreMap
AUD-749
=> [AUD-749] Add info for remixables to exploreMap

src/servlets/utils/helpers.ts
Mimics: https://github.com/AudiusProject/audius-client/pull/583
=> Fallback to old routing logic on 404

.circleci/config.yml, README.md, package-lock.json, package.json, src/index.ts, tsconfig.json
* Hot reloading
* Typescript via node-ts
TESTS:
* npm run start:stage
* embed player against local GA
* docker-compose up -d
=> Add some startup ergonomics

package-lock.json, package.json, src/servlets/metaTags/index.ts, src/servlets/utils/helpers.ts
Updates getTrackContext to be able to sort out the response whether the tracks API used to get the track was `/tracks` or `/v1/tracks`
=> Update getTrackContext to work whether retrieving the track from /v1/tracks or /tracks

.env.prod, .env.stage, package-lock.json, package.json, src/index.ts, src/servlets/bedtime/helpers.ts, src/servlets/bedtime/index.ts, src/servlets/bedtime/types.ts, tslint.json
Added fetch-nft library to GA and add route for collectible detail and collectible gallery
=> [AUD-1030] Add bedtime routes for collectibles

src/index.ts
Updating api routes for collectibles to match expected format
=> Update api routes for collectibles

src/index.ts
Temporarily updating the collectible metatag routes for testing
=> Update collectibles metatag routes for testing

package-lock.json, package.json
=> Bump fetch-nft to 0.1.2

package-lock.json, package.json
=> Bump fetch-nft to 0.1.3

src/index.ts, src/servlets/metaTags/index.ts, src/servlets/metaTags/types.ts, src/servlets/utils/constants.ts
Added signup ref route.
Defaults to default when to ref query param is present
=> Add route for signup referrals

src/servlets/metaTags/index.ts
=> Add @ for signup ref handle

src/index.ts
Add route for audio nft playlist.
Linter also removed a few commas
=> Add route for audio nft playlist

src/servlets/ipfs/index.ts
=> Add dht provide recursive after pin

package-lock.json, package.json, src/libs.ts, src/servlets/api/index.ts, src/servlets/bedtime/index.ts, src/servlets/ipfs/index.ts, src/servlets/proxy/index.ts, tsconfig.json
Requires changes here: https://github.com/AudiusProject/audius-protocol/pull/3360
Res:
```
{
data: [
"https://audius-metadata-3.figment.io/",
"https://audius-disco.ams-x01.nl.supercache.org/",
"https://audius-metadata-5.figment.io/",
"https://audius-metadata-2.figment.io/",
"https://audius-disco.dfw-x02.us.supercache.org/",
"https://blockdaemon-audius-discovery-01.bdnodes.net/",
"https://audius-dp.amsterdam.creatorseed.com/",
"https://audius-dp.singapore.creatorseed.com/",
"https://blockdaemon-audius-discovery-03.bdnodes.net/",
"https://blockdaemon-audius-discovery-08.bdnodes.net/",
"https://blockdaemon-audius-discovery-04.bdnodes.net/",
"https://blockdaemon-audius-discovery-02.bdnodes.net/",
"https://blockdaemon-audius-discovery-06.bdnodes.net/",
"https://audius-metadata-1.figment.io/", …
```
=> [C-467] Filter api endpoints to available services at current version

package-lock.json, package.json
like https://github.com/AudiusProject/audius-protocol/pull/5605
Tested:
- Ran GA against prod, hit localhost:8000/api which shows usable discoverynodes
=> Upgrade sdk in general admission

src/servlets/utils/constants.ts
Add premium tracks unfurl link
=> [PAY-2111] Add premium tracks og tag

src/servlets/metaTags/index.ts, src/servlets/metaTags/template.html, src/servlets/metaTags/types.ts
adds farcaster frame functionality to GA
to test:
npm i 
update .env.prod to have the correct eth RPC
npm run start:prod
ngrok http http://localhost:8000
use the frame validator and point to your ngrok instance!
=> farcaster frame

src/servlets/api/index.ts
- improve the reliability of api.audius.co
=> rm other nodes

.env.prod, .env.stage, src/index.ts, src/servlets/metaTags/index.ts, src/servlets/metaTags/template.html, src/servlets/metaTags/types.ts, src/servlets/utils/helpers.ts, src/types/Comment.ts
* Update track route to handle comment response if commentId query param is present
* Update comment context to link to OG repo for image generation
=> [PE-6480, PE-6484] Add support for track comment responses and og image generation

src/servlets/metaTags/index.ts
Small update to make sure that invalid comment ids will not display when on a different track
=> Add fallback when the comment id provided is for a different track

package.json, src/servlets/metaTags/index.ts, src/servlets/utils/helpers.ts, src/types/User.ts
- Fixes a big issue where user_id not a part of api response. Using id instead + that is already encoded.
- Fixes issue with GA unfurls not working for users, since we were checking user_id. Added fallback to non og-route if entityId not available for whatever reason.
- lint:fix all the things
=> Fix user model and routes

src/servlets/metaTags/index.ts, src/servlets/metaTags/template.html, src/servlets/metaTags/types.ts
Adds OEmbed support for GA in case the UA is treated as a bot (Reddit won't be afaict, but good to have coverage)
=> Add OEmbed support
